[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "rust_read_extraction"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
module-name = "rust_read_extraction"
