[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "build_phasing_graph"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
# Native extension module name for import
module-name = "build_phasing_graph"
